// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwhxguflmceujvrhnkjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3aHhndWZsbWNldWp2cmhua2pkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NzI5OTgsImV4cCI6MjA3MDM0ODk5OH0.rqMiHqR0mpAyYVIMDfKQ2r_kIDvBp9ylzdsCHz4XPfc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});